language: python
python:
  - "3.6"
cache: pip
install:
  # Reducing verbosity is needed because of Travis' limit on log length
  - pip install -r requirements.txt --quiet
script:
  - python -m unittest discover
